unity:
  force_https_callbacks: False
  bypass_callback_validation: False
  
upload:
  max_content_length: 64

flask:
  secret_key: "your_secure_key_here"
  secure_cookie: True

crypto:
  cookie_key: "your_cookie_key_here"

database:
  db: 
  user: 
  pass: 
  
restfulsleep:
  server: 'http://localhost:2581'
  psk: 'restfulsleep_security_key'

backblaze:
  bucket-name: 
  key-id: 
  auth-key: 