"""add intents to application

Revision ID: 1b6be2a1b94c
Revises: bef116270b36
Create Date: 2026-04-14 00:26:12.620670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6be2a1b94c'
down_revision: Union[str, Sequence[str], None] = 'bef116270b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('intents', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'intents')
    # ### end Alembic commands ###
