"""update team member table

Revision ID: 3cf3d8c5ecc3
Revises: 8dd3d18798b3
Create Date: 2026-04-04 14:37:07.835861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf3d8c5ecc3'
down_revision: Union[str, Sequence[str], None] = '8dd3d18798b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_member', sa.Column('team_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('team_member_team_fkey'), 'team_member', type_='foreignkey')
    op.create_foreign_key(None, 'team_member', 'team', ['team_id'], ['id'])
    op.drop_column('team_member', 'team')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_member', sa.Column('team', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'team_member', type_='foreignkey')
    op.create_foreign_key(op.f('team_member_team_fkey'), 'team_member', 'team', ['team'], ['id'])
    op.drop_column('team_member', 'team_id')
    # ### end Alembic commands ###
