"""add oauth_id and client_secret to application

Revision ID: 5720dea8220b
Revises: 1b6be2a1b94c
Create Date: 2026-04-14 19:10:01.311393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5720dea8220b'
down_revision: Union[str, Sequence[str], None] = '1b6be2a1b94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('oauth_id', sa.String(length=255), nullable=True))
    op.add_column('application', sa.Column('client_secret', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_application_oauth_id'), 'application', ['oauth_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_oauth_id'), table_name='application')
    op.drop_column('application', 'client_secret')
    op.drop_column('application', 'oauth_id')
    # ### end Alembic commands ###
