"""update session table

Revision ID: 8dd3d18798b3
Revises: ef51a2688137
Create Date: 2026-04-02 22:44:50.233186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd3d18798b3'
down_revision: Union[str, Sequence[str], None] = 'ef51a2688137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('session_token', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('session_refresh_token_key'), 'session', type_='unique')
    op.create_unique_constraint(None, 'session', ['session_token'])
    op.drop_column('session', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'session', type_='unique')
    op.create_unique_constraint(op.f('session_refresh_token_key'), 'session', ['refresh_token'], postgresql_nulls_not_distinct=False)
    op.drop_column('session', 'session_token')
    # ### end Alembic commands ###
