"""remove webhook_logs attempt

Revision ID: 905bc334ee00
Revises: eedd6211d65b
Create Date: 2026-03-18 02:41:30.087089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905bc334ee00'
down_revision: Union[str, Sequence[str], None] = 'eedd6211d65b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_logs', 'attempt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_logs', sa.Column('attempt', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
