"""update application team to team_id

Revision ID: bef116270b36
Revises: 610093972bab
Create Date: 2026-04-06 03:27:21.692946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef116270b36'
down_revision: Union[str, Sequence[str], None] = '610093972bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('team_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('application_team_fkey'), 'application', type_='foreignkey')
    op.create_foreign_key(None, 'application', 'team', ['team_id'], ['id'])
    op.drop_column('application', 'team')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('team', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.create_foreign_key(op.f('application_team_fkey'), 'application', 'team', ['team'], ['id'])
    op.drop_column('application', 'team_id')
    # ### end Alembic commands ###
